myPrompts = [ "Some ways I could honor negative emotions without judgment are…",
"If I were to adopt a new way of seeing this struggle, I would like to believe things like… ",
"The primary feelings I want to bring to life are…",
"Three questions I could ask myself every morning to encourage positive energy are…",
"Some things I could say out loud to affirm my desired feelings (affirmations) are…",
"Some other ways I could remind myself of how I want to feel are…",
"If I could influence others to feel a particular way, I would encourage them to feel…",
"Who might need me to role model authentic compassion right now?",
"If I were to approach my relationships, activities, and projects as a better role model for authentic compassion, the things I would start doing are…",
"Some things I might say to a friend struggling with their emotions and feelings are…",
"The things that help me the most right now are…",
"What can I do in this moment to get myself some nourishment and self-care?",
"I am thankful that I…",
"How might this stressful experience transform me into a more loving (compassionate, forgiving, patient, helpful, or faithful) person?",
"What past challenge has turned out to be a gift in disguise (even if it’s still painful)? Why? What was the silver lining?",
"What’s not wrong in my life? Here are three things that I can think of right now:",
"If I knew that anything I asked for would be answered, I would ask for ________.",
"What do I want my life to FEEL like?",
"Right now, I feel challenged by ________. I feel supported when ________.",
"I have been paying a lot of attention to ________. I would like to pay more attention to _______",
"I can devote more energy to the better-feeling alternatives by ________.",
"What’s one hard lesson you’re grateful life taught you in the past year?",
"What’s something you’ve moved on from that once meant the world to you?  And, what’s something you love today that you never even knew you needed in your life?",
"What’s one unchangeable reality you’re still holding on to and resisting?  What can you do right now to ease your mind into the acceptance of this reality?",
"Who would you be, and what else would you see about your present life situation, if you removed the thought that’s been worrying you?",
"How has your daily environment been affecting you recently?",
"What’s one small example of how you have \"customized\" your life for the better?",
"What have your actions over the past year been saying about how you prioritize your personal growth?  What kind of silent progress would you like to make in your life by the end of 2019?",
"ure out where your energy goes, and remove distractions.  It’s time to focus on what matters.",
"What’s one distraction that has been getting the best of you lately?  Why?",
"What’s one small risk you believe is worth taking this year?  What’s the first step?",
"What’s something big you’ve accomplished in the past that once seemed impossible?",
"Why are you ready to make positive changes?  Why is the journey in front of you worth the extra effort?",
"How can you give yourself a little extra time and space to make the right decisions on a daily basis?",
"What’s one thing you would do differently if you knew no one would judge you?",
"What’s one good, recent example of someone with a negative attitude completely misjudging you?  How did you handle it, and what did you learn?",
"Who was the last person who was unexpectedly kind to you?  What can you easily do to be a little kinder than usual today, and beyond?",
"What makes your significant other (or someone else you love) truly beautiful on the inside?  What make YOU truly beautiful on the inside?",
"What’s something true about yourself that you need to embrace more openly and lovingly in the year ahead?",
"There’s always room for a new idea, a new step… a new beginning.",
"What does \"a new beginning\" mean to you right now?",
"Write a list of 10 things you are grateful for today.",
"What makes YOU unique?",
"Reflect on one of the greatest life lessons you’ve ever learned. What was it and what did you learn? Perhaps you’ve forgotten what you learned – how could you incorporate those learnings into the way you live today?",
"How have you changed from the person you were 5 years ago? Is this positive?",
"Write a letter to your teenage self.",
"If you could run away, where would you go and why? Would you take anyone with you?",
"Reflect on the happiest moment of your life. Where were you, what were you doing, and who were you sharing it with? Reflect on every detail.",
"Make a list of your priorities for the week, month or year. Are these aligned to what you really want to be doing in life?",
"What is your most treasured possession and why?",
"Make a list of the people in your life who genuinely believe in and support you. Explore why their support means so much to you.",
"Share one of your innermost secrets, something you’ve never told anyone.",
"Who means the world to you and why? What traits of there’s do you value?",
"What can you do or change in your life to focus more on your health and wellbeing? Be honest.",
"Write a letter to your body telling it how you feel? This could be a love letter or letter of apology if you have been critical of your body in the past like me.",
"Write about your day or week so far. Did something good or bad happen? Are you feeling happy or sad? Did you learn or do something new?",
"How would you like to be remembered when you’re gone?",
"If you could change one thing, what would it be and why. Or perhaps you wouldn’t change a thing. Why is that so?",
"What makes you feel at peace?",
"How would you describe yourself to a stranger?",
"What natural gift would you most like to possess?",
"What is the best compliment you’ve ever received?",
"What do you think is the most unique thing about you? Do you keep it hidden or let it show?",
"What would your childhood self love about your current self?",
"What do you consider the best year of your life so far, and what made it so great?",
"How do you want to be remembered?",
"If my body could talk, it would say…",
"I feel happiest in my skin when…",
"I feel proud of myself when…",
"I feel safe when…",
"I forgive myself for...",
"I no longer need…",
"If I could give my teenage self some advice, I would tell her…",
"The last positive thing I was a part of…",
"Today I accomplished…",
"Ten things that bring me peace are…",
"I deserve love because…",
"Five things I’m grateful for today are…",
"My perfect day looks like…",
"A beautiful person is…",
"What is the best compliment you’ve ever received?",
"What emotions do you feel or associate with confidence?",
"What are questions to which you need urgent answers to?",
"What qualities do you deserve in a romantic partner?",
"What positive character traits do you have?",
"What will you accomplish in the next five years?",
"Why do you think it’s important to have high self esteem?",
"What are things you’d like to say ‘no’ to?",
"Who appreciates you?",
"What makes you unique?",
"What would you do if you could live a day without consequences?",
"How do you indulge yourself? How can you indulge yourself more often?",
"Who are your role models/idols? How are you already like them?",
"What is ‘enough’ for you?",
"What would your teenage self love about you now?",
"What does your best friend brag about when she talks about you?",
"What makes you feel strong or invincible?",
"What are times that make it very difficult for you to say \"no\" and what are some default responses you can come up with for next time?",
"What is an area of life you could use help with and what are some resources you could utilize to get assistance?",
"What are you good at helping other people at?",
"What is something you need to let go of?",
"What area of yourself is it hardest to receive a compliment about?",
"When was the last time you were a badass?",
"What do you love about your life?",
"When does your physical body feel happy?",
"Write a pep talk to give yourself the next time you feel sad, upset, or full of doubt.",
"Write a letter to your future-self.",
"Write a love letter to your least favorite part of your body.",
"What are your morals? What is important to you ethically? Think about things that are unbending parts of your value system that you refuse to compromise and then explain why.",
"Fill in the blanks: I have the most incredible __________. When I walk into a room people feel __________. It’s very easy for me to __________ because I’m so __________. I will continue to kick ass at ",
"Today, I choose to let go of the things I can’t control, including…",
"I recognize that I don’t need to have all the answers right now. Today, I give myself permission not to know…",
"Dear inner critic: You always focus on everything I’m doing wrong, but I know I’m doing a lot right, including…",
"I know I’m strong enough to handle whatever comes at me, because I’ve survived a lot, including…",
"My favorite way to spend the day is…",
"The words I’d like to live by are…",
"I couldn’t imagine living without…",
"When I’m in pain — physical or emotional — the kindest thing I can do for myself is…",
"Make a list of the people in your life who genuinely support you, and who you can genuinely trust. (Then make time to hang out with them.)",
"What does unconditional love look like for you?",
"What would you do if you loved yourself unconditionally? How can you act on these things whether you do or don’t?",
"I really wish others knew this about me…",
"Name what is enough for you.",
"If my body could talk, it would say…",
"Name a compassionate way you’ve supported a friend recently. Then write down how you can do the same for yourself.",
"What do you love about life?",
"Write about a time when work felt real to you, necessary and satisfying. Paid or unpaid, professional or domestic, physical or mental.",
"Write about your first love — whether a person, place or thing.",
"Using 10 words, describe yourself.",
"What’s surprised you the most about your life or life in general?",
"What can you learn from your biggest mistakes?",
"I feel most energized when…",
"Write a list of questions to which you urgently need answers.",
"Make a list of everything that inspires you — from books to websites to quotes to people to paintings to stores to the stars.",
"What’s one topic you need to learn more about to help you live a more fulfilling life?",
"I feel happiest in my skin when…",
"Make a list of everything you’d like to say no to.",
"Make a list of everything you’d like to say yes to.",
"Write the words you need to hear." ];

