myPrompts = [ 
"What would make what I am doing right now easiest?",
"What is something that doesn't make sense?",
"What is something I would miss if I no longer had it?",
"What is one relationship that I have let slip? What is the reason?",
"One thing I've always wished for is...",
"If I received $10,000 that I HAD to spend on myself, I would...",
"One thing I know I need to work on is...",
"I'm most proud that I...",
"In the next year, I really want to...",
"If I could ask any person just one thing, they would be ____ and I would ask...",
"A silver lining in a not so good situation that happened recently is...",
"The skill I've always wanted to have is...",
"The ways I've grown over the past 5 years are...",
"Something I'd like to achieve one day is...",
"The best bit of advice I could give to a younger me is...",
"A book that I always re-read is _____, because...",
"One thing I'll never regret is ______, because...",
"The quality I admire most in others is...",
"If I could be a go-to person for anything, it would be...",
"If I could go to any point in the past or future, I would...",
"The thing that I'm most afraid to tell people is...",
"The thing that I'm most thankful for is...",
"When people first meet me, I hope they feel...",
"Something that I'd love to do today (that I can easily do!) is...",
"My current day-to-day life looks like...",
"If I had to give myself an alignment rating from 1-5 (1 being misaligned and 5 being very aligned) for the main areas of my life right now, how would I rate them at the present moment and why? Areas of focus may include: Relationships, Career, Physical Health, Spiritual Health, Mindset, Self-care",
"How have I gotten in my own way?",
"What do I want to let go of?",
"How do I want to feel?",
"What words of wisdom would my ideal future self give me right now?",
"How do I visualize myself in the future?",
"The feelings I've been experiencing a lot of lately are...",
"The things that have been causing me tension lately are...",
"The areas of life where I'm not experiencing the feelings I want to are...",
"The feelings I want to experience more of in life include...",
"The activities, projects, and people that bring me the most joy, meaning, and connection are...",
"Some things I could stop doing so I could better align with how I want to feel are...",
"If I was going to add something that brought more meaning, joy, and enthusiasm into my life, I would add...",
"The next time I experience a negative emotion, I am going to...",
"Some ways I could honor negative emotions without judgment are...",
"If I were to adopt a new way of seeing this struggle, I would like to believe things like...",
"The primary feelings I want to bring to life are...",
"Three questions I could ask myself every morning to encourage positive energy are...",
"Some things I could say out loud to affirm my desired feelings (affirmations) are...",
"Some other ways I could remind myself of how I want to feel are...",
"If I could influence others to feel a particular way, I would encourage them to feel...",
"Who might need me to role model authentic compassion right now?",
"If I were to approach my relationships, activities, and projects as a better role model for authentic compassion, the things I would start doing are...",
"Some things I might say to a friend struggling with their emotions and feelings are...",
"The things that help me the most right now are...",
"What can I do in this moment to get myself some nourishment and self-care?",
"I am thankful that I...",
"How might this stressful experience transform me into a more loving (compassionate, forgiving, patient, helpful, or faithful) person?",
"What past challenge has turned out to be a gift in disguise (even if it's still painful)? Why?\nWhat was the silver lining?",
"What's not wrong in my life?\nHere are three things that I can think of right now:",
"If I knew that anything I asked for would be answered, I would ask for ________.",
"What do I want my life to FEEL like?",
"Right now, I feel challenged by ________.\nI feel supported when ________.",
"I have been paying a lot of attention to ________.\nI would like to pay more attention to _______",
"I can devote more energy to the better-feeling alternatives by ________.",
"What's one hard lesson you're grateful life taught you in the past year?",
"What's something you've moved on from that once meant the world to you?\n And, what's something you love today that you never even knew you needed in your life?",
"What's one unchangeable reality you're still holding on to and resisting?\n What can you do right now to ease your mind into the acceptance of this reality?",
"Who would you be, and what else would you see about your present life situation, if you removed the thought that's been worrying you?",
"How has your daily environment been affecting you recently?",
"What's one small example of how you have \"customized\" your life for the better?",
"What have your actions over the past year been saying about how you prioritize your personal growth?\n What kind of silent progress would you like to make in your life by the end of 2019?",
"ure out where your energy goes, and remove distractions.\n It's time to focus on what matters.",
"What's one distraction that has been getting the best of you lately?\n Why?",
"What's one small risk you believe is worth taking this year?\n What's the first step?",
"What's something big you've accomplished in the past that once seemed impossible?",
"Why are you ready to make positive changes?\n Why is the journey in front of you worth the extra effort?",
"How can you give yourself a little extra time and space to make the right decisions on a daily basis?",
"What's one thing you would do differently if you knew no one would judge you?",
"What's one good, recent example of someone with a negative attitude completely misjudging you?\n How did you handle it, and what did you learn?",
"Who was the last person who was unexpectedly kind to you?\n What can you easily do to be a little kinder than usual today, and beyond?",
"What makes your significant other (or someone else you love) truly beautiful on the inside?\n What make YOU truly beautiful on the inside?",
"What's something true about yourself that you need to embrace more openly and lovingly in the year ahead?",
"There's always room for a new idea, a new step...\na new beginning.",
"What does \"a new beginning\" mean to you right now?",
"Write a list of 10 things you are grateful for today.",
"What makes YOU unique?",
"Reflect on one of the greatest life lessons you've ever learned.\nWhat was it and what did you learn?\nPerhaps you've forgotten what you learned – how could you incorporate those learnings into the way you live today?",
"How have you changed from the person you were 5 years ago?\nIs this positive?",
"Write a letter to your teenage self.",
"If you could run away, where would you go and why?\nWould you take anyone with you?",
"Reflect on the happiest moment of your life.\nWhere were you, what were you doing, and who were you sharing it with?\nReflect on every detail.",
"Make a list of your priorities for the week, month or year.\nAre these aligned to what you really want to be doing in life?",
"What is your most treasured possession and why?",
"Make a list of the people in your life who genuinely believe in and support you.\nExplore why their support means so much to you.",
"Share one of your innermost secrets, something you've never told anyone.",
"Who means the world to you and why?\nWhat traits of there's do you value?",
"What can you do or change in your life to focus more on your health and wellbeing?\nBe honest.",
"Write a letter to your body telling it how you feel?\nThis could be a love letter or letter of apology if you have been critical of your body in the past like me.",
"Write about your day or week so far.\nDid something good or bad happen?\nAre you feeling happy or sad?\nDid you learn or do something new?",
"How would you like to be remembered when you're gone?",
"If you could change one thing, what would it be and why.\nOr perhaps you wouldn't change a thing.\nWhy is that so?",
"What makes you feel at peace?",
"How would you describe yourself to a stranger?",
"What natural gift would you most like to possess?",
"What is the best compliment you've ever received?",
"What do you think is the most unique thing about you?\nDo you keep it hidden or let it show?",
"What would your childhood self love about your current self?",
"What do you consider the best year of your life so far, and what made it so great?",
"How do you want to be remembered?",
"If my body could talk, it would say...",
"I feel happiest in my skin when...",
"I feel proud of myself when...",
"I feel safe when...",
"I forgive myself for...",
"I no longer need...",
"If I could give my teenage self some advice, I would tell her...",
"The last positive thing I was a part of...",
"Today I accomplished...",
"Ten things that bring me peace are...",
"I deserve love because...",
"Five things I'm grateful for today are...",
"My perfect day looks like...",
"A beautiful person is...",
"What is the best compliment you've ever received?",
"What emotions do you feel or associate with confidence?",
"What are questions to which you need urgent answers to?",
"What qualities do you deserve in a romantic partner?",
"What positive character traits do you have?",
"What will you accomplish in the next five years?",
"Why do you think it's important to have high self esteem?",
"What are things you'd like to say ‘no' to?",
"Who appreciates you?",
"What makes you unique?",
"What would you do if you could live a day without consequences?",
"How do you indulge yourself?\nHow can you indulge yourself more often?",
"Who are your role models/idols?\nHow are you already like them?",
"What is ‘enough' for you?",
"What would your teenage self love about you now?",
"What does your best friend brag about when she talks about you?",
"What makes you feel strong or invincible?",
"What are times that make it very difficult for you to say \"no\" and what are some default responses you can come up with for next time?",
"What is an area of life you could use help with and what are some resources you could utilize to get assistance?",
"What are you good at helping other people at?",
"What is something you need to let go of?",
"What area of yourself is it hardest to receive a compliment about?",
"When was the last time you were a badass?",
"What do you love about your life?",
"When does your physical body feel happy?",
"Write a pep talk to give yourself the next time you feel sad, upset, or full of doubt.",
"Write a letter to your future-self.",
"Write a love letter to your least favorite part of your body.",
"What are your morals?\nWhat is important to you ethically?\nThink about things that are unbending parts of your value system that you refuse to compromise and then explain why.",
"Fill in the blanks: I have the most incredible __________.\nWhen I walk into a room people feel __________.\nIt's very easy for me to __________ because I'm so __________.\nI will continue to kick ass at ",
"Today, I choose to let go of the things I can't control, including...",
"I recognize that I don't need to have all the answers right now.\nToday, I give myself permission not to know...",
"Dear inner critic: You always focus on everything I'm doing wrong, but I know I'm doing a lot right, including...",
"I know I'm strong enough to handle whatever comes at me, because I've survived a lot, including...",
"My favorite way to spend the day is...",
"The words I'd like to live by are...",
"I couldn't imagine living without...",
"When I'm in pain — physical or emotional — the kindest thing I can do for myself is...",
"Make a list of the people in your life who genuinely support you, and who you can genuinely trust.\n(Then make time to hang out with them.)",
"What does unconditional love look like for you?",
"What would you do if you loved yourself unconditionally?\nHow can you act on these things whether you do or don't?",
"I really wish others knew this about me...",
"Name what is enough for you.",
"If my body could talk, it would say...",
"Name a compassionate way you've supported a friend recently.\nThen write down how you can do the same for yourself.",
"What do you love about life?",
"Write about a time when work felt real to you, necessary and satisfying.\nPaid or unpaid, professional or domestic, physical or mental.",
"Write about your first love — whether a person, place or thing.",
"Using 10 words, describe yourself.",
"What's surprised you the most about your life or life in general?",
"What can you learn from your biggest mistakes?",
"I feel most energized when...",
"Write a list of questions to which you urgently need answers.",
"Make a list of everything that inspires you — from books to websites to quotes to people to paintings to stores to the stars.",
"What's one topic you need to learn more about to help you live a more fulfilling life?",
"I feel happiest in my skin when...",
"Make a list of everything you'd like to say no to.",
"Make a list of everything you'd like to say yes to.",
"Write the words you need to hear.",
"Abandon normal instruments",
"Accept advice",
"Accretion",
"A line has two sides",
"Allow an easement (an easement is the abandonment of a stricture)",
"Are there sections?\nConsider transitions",
"Ask people to work against their better judgement",
"Ask your body",
"Assemble some of the instruments in a group and treat the group",
"Balance the consistency principle with the inconsistency principle",
"Be dirty",
"Breathe more deeply",
"Bridges -build -burn",
"Cascades",
"Change instrument roles",
"Change nothing and continue with immaculate consistency",
"Children's voices -speaking -singing",
"Cluster analysis",
"Consider different fading systems",
"Consult other sources -promising -unpromising",
"Convert a melodic element into a rhythmic element",
"Courage!",
  "Cut a vital connection",
  "Decorate, decorate",
"Define an area as 'safe' and use it as an anchor",
"Destroy -nothing -the most important thing",
"Discard an axiom",
"Disconnect from desire",
"Discover the recipes you are using and abandon them",
"Distorting time",
"Do nothing for as long as possible",
"Don't be afraid of things because they're easy to do",
  "Don't be frightened of cliches",
"Don't be frightened to display your talents",
"Don't break the silence",
"Don't stress one thing more than another",
"Do something boring",
"Do the washing up",
"Do the words need changing?",
    "Do we need holes?",
    "Emphasise differences",
"Emphasise repetitions",
"Emphasise the flaws",
"Faced with a choice, do both",
"Feedback recordings into an acoustic situation",
"Fill every beat with something",
    "Get your neck massaged",
"Ghost echoes",
"Give the game away",
"Give way to your worst impulse",
"Go slowly all the way round the outside",
"Honor thy error as a hidden intention",
"How would you have done it?",
    "Humanise something free of error",
"Imagine the music as a moving chain or caterpillar",
"Imagine the music as a set of disconnected events",
"Infinitesimal gradations",
"Intentions -credibility of -nobility of -humility of",
"Into the impossible",
"Is it finished?",
    "Is there something missing?",
    "Is the tuning appropriate?",
    "Just carry on",
"Left channel, right channel, centre channel",
"Listen in total darkness, or in a very large room, very quietly",
"Listen to the quiet voice",
"Look at a very small object, look at its centre",
"Look at the order in which you do things",
    "Look closely at the most embarrassing details and amplify them",
"Lowest common denominator check -single beat -single note -single riff",
"Make a blank valuable by putting it in an exquisite frame",
"Make an exhaustive list of everything you might do and do the last thing on the list",
"Make a sudden, destructive unpredictable action; incorporate",
"Mechanicalise something idiosyncratic",
"Mute and continue",
"Only one element of each kind",
"(Organic) machinery",
"Overtly resist change",
"Put in earplugs",
"Remember those quiet evenings",
"Remove ambiguities and convert to specifics",
"Remove specifics and convert to ambiguities",
"Repetition is a form of change",
"Reverse",
"Shut the door and listen from outside",
"Simple subtraction",
"Spectrum analysis",
"Take a break",
"Take away the elements in order of apparent non-importance",
"Tape your mouth",
"The inconsistency principle",
"The tape is now the music",
"Think of the radio",
"Tidy up",
"Trust in the you of now",
"Turn it upside down",
"Twist the spine",
"Use an old idea",
"Use an unacceptable colour",
"Use fewer notes",
"Use filters",
"Use 'unqualified' people",
    "Short circuit (example; a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
"Water",
"What are you really thinking about just now?\nIncorporate",
    "What is the reality of the situation?",
    "What mistakes did you make last time?",
    "What would your closest friend do?",
    "What wouldn't you do?",
"Work at a different speed",
"You are an engineer",
"You can only make one dot at a time",
"You don't have to be ashamed of using your own ideas",
    "(Organic) machinery.",
    "A line has two sides",
    "A very small object - its centre",
    "Abandon desire",
    "Abandon normal instructions",
    "Accept advice",
    "Accretion",
    "Adding on",
    "Allow an easement\n(an easement is the abandonment of a stricture)",
    "Always give yourself credit for having more than personality",
    "Always the first steps",
    "Animal noises",
    "Are there sections? Consider transitions",
    "Ask a computer program to repeat your last action",
    "Ask people to work against their better judgement",
    "Ask your body",
    "Assemble some of the elements in a group and treat the group",
    "Back up a few steps What else could you have done?",
    "Balance the consistency principle with the inconsistency principle",
    "Be dirty",
    "Be extravagant",
    "Be less critical more often",
    "Breathe more deeply",
    "Build bridges",
    "Burn bridges",
    "Call your mother and ask her what to do",
    "Cascades",
    "Change ambiguities to specifics",
    "Change specifics to ambiguities",
    "Change instrument roles",
    "Change nothing and continue with immaculate consistency",
    "Childrenâ€™s voices speaking",
    "Childrenâ€™s voices singing",
    "Cluster analysis",
    "Consider different fading systems",
    "Consider transitions",
    "Consult other promising sources",
    "Consult other unpromising sources",
    "Convert a melodic element into a rhythmic element",
    "Courage!",
    "Cut a vital connection",
    "Cut a virtual connection",
    "Decorate, decorate",
    "Describe the landscape in which this belongs",
    "Destroy nothing",
    "Discard an axiom",
    "Disciplined self-indulgence",
    "Disconnect from desire",
    "Discover the recipes you are using and abandon them",
    "Discover your formulas and abandon them",
    "Display your talent",
    "Distorting time",
    "Do nothing for as long as possible",
    "Do something boring",
    "Do something sudden, destructive and unpredictable",
    "Do the last thing first",
    "Do the washing up",
    "Do the words need changing?",
    "Do we need holes?",
    "Don't avoid what is easy",
    "Don't be afraid of things because they're easy to do",
    "Don't be frightened of cliches",
    "Don't be frightened to display your talents",
    "Don't break the silence",
    "Don't stress one thing more than another",
    "Emphasize differences",
    "Emphasize repetitions",
    "Emphasize the flaws",
    "Faced with a choice, do both!",
    "Feed the recording back out of the medium",
    "Feedback recordings into an acoustic situation",
    "Fill every beat with something",
    "First work alone, then work in unusual pairs",
    "From nothing to more than nothing",
    "Get your neck massaged",
    "Ghost echoes",
    "Give the game away",
    "Give way to your worst impulse",
    "Go outside. Shut the door",
    "Go slowly all the way round the outside",
    "Go to an extreme, move back to a more comfortable place",
    "How would someone else do it?",
    "How would you explain this to your parents?",
    "How would you have done it?",
    "Humanize something that is free of error",
    "Idiot glee",
    "Imagine the music as a moving chain or caterpillar",
    "Imagine the music as a series of disconnected events",
    "In total darkness",
    "In a very large room, very quietly",
    "Infinitesimal gradations",
    "Instead of changing the thing, change the world around it",
    "Credibility of intentions",
    "Nobility of intentions",
    "Humility of intentions",
    "Is it finished?",
    "Is something missing?",
    "Is the style right?",
    "Is the tuning appropriate?",
    "It is quite possible (after all)",
    "It is simply a matter or work",
    "Just carry on",
    "Left channel, right channel, centre channel",
    "List the qualities it has List those you'd like",
    "Listen in total darkness",
    "Listen in a very large room, very quietly",
    "listen to the quiet voice",
    "Look at a very small object, look at its centre",
    "Look at the order in which you do things",
    "Look closely at the most embarrassing details and amplify",
    "Lost in useless territory",
    "Lowest common denominator check: single beat; single note; single riff",
    "Magnify the most difficult details",
    "Make a blank valuable by putting it in an excquisite frame",
    "Make a sudden, destructive unpredictable action. Incorporate",
    "Make an exhaustive list of everything you might do and do the last thing on the list",
    "Make it more sensual",
    "Make it more banal",
    "Make what's perfect more human",
    "Mechanize something idiosyncratic",
    "Move towards the impossible",
    "Move towards the unimportant",
    "Mute and continue",
    "Not building a wall but making a brick",
    "Once the search is in progress, something will be found",
    "Only a part, not the whole",
    "Only one element of each kind",
    "Overtly resist change",
    "Pae White's non-blank graphic metacard",
    "Pay attention to distractions",
    "Picture of a man spotlighted",
    "Put in earplugs",
    "Question the heroic approach",
    "Rearrange",
    "Remember those quiet evenings",
    "Remove a restriction",
    "Remove ambiguities and convert to specifics",
    "Remove specifics and convert to ambiguities",
    "Remove the middle, extend the edges",
    "Repetition is a form of change",
    "Retrace your steps",
    "Revaluation\n(a warm feeling)",
    "Reverse",
    "Short circuit",
    "Shut the door and listen from outside",
    "Simple subtraction",
    "Simply a matter of work",
    "Slow preparation, fast execution",
    "Spectrum analysis",
    "State the problem in words as simply as possible",
    "Steal a solution",
    "Take a break",
    "Take away as much mystery as possible What is left?",
    "Take away the elements in order of apparent non-importance",
    "Take away the important parts",
    "Tape your mouth",
    "The inconsistency principle",
    "The most important thing is the thing most easily forgotten",
    "The tape is now the music",
    "Think inside the work",
    "Think outside the work",
    "Think of the radio",
    "Tidy up",
    "Towards the insignificant",
    "Trust in the you of now",
    "Try faking it",
    "Turn it upside down",
    "Twist the spine",
    "Use â€œunqualifiedâ€ people",
    "Use an old idea",
    "Use an unacceptable color",
    "Use cliches",
    "Use fewer notes",
    "Use filters",
    "Use something nearby as a model",
    "Use your own ideas",
    "Voice your suspicions",
    "Water",
    "Fire",
    "Earth",
    "Wind",
    "Heart",
    "What are the sections sections of?",
    "What context would look right?",
    "What do you do?",
    "Now, what do you do best?",
    "What else is this like?",
    "What is the reality of the situation?",
    "What is the simplest solution?",
    "What mistakes did you make last time?",
    "What most recently impressed you?",
    "What can you learn from it?",
    "How is it similar?",
    "What could you take from it?",
    "What to increase?\nWhat to reduce?\nWhat to maintain?",
    "What were the branch points in the evolution of this entity?",
    "What were you really thinking about just now? Incorporate",
    "What would make this really successful?",
    "What would your closest friend do?",
    "What wouldn't you do? Do that",
    "When is it for?",
    "Who is it for?",
    "Where is the edge?",
    "Which parts can be grouped?",
    "Who would make this really successful?",
    "Work at a different speed",
    "Would anyone want it?",
    "You are an engineer",
    "You can only make one dot at a time",
    "You don't have to be ashamed of using your own ideas",
    "Your mistake was a hidden intention"
];
